### ISSUE TITLE
serch results with search term: -19 5 1991 

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#10]
A search with the search terms

Stefan Eins    hrsg  zum Anlass der 157  Wechselausstellung der Oesterreichischen Galerie   Wien, im Oberen Belvedere, 24 4  -19 5 1991

returns more than 7 Mio hits

using 
Stefan Eins    hrsg  zum Anlass der 157  Wechselausstellung der Oesterreichischen Galerie   Wien, im Oberen Belvedere, 24 4  19 5 1991

(witout the hyphen) returns the correct (1 item) result

**Comment by liowalter** [comment]
This is a feature from Vufind : space followed by - has a special meaning in the search (exclude the term)
