### ISSUE TITLE
Behandlung des Fragezeichens (Metacharacter oder nicht)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#11]
Suche
1) Pierre Teilhard de Chardin: Wegbereiter des New Age?
-> wird nicht gefunden (Doppelpunkt wird bereits von der Applikation gefiltert)
(issue im User feedback)
-> sollte nach meinem Ermessen gefunden werden, da Metacharacter ? auch das Literal '?' finden sollte (0 oder 1 Character)

2) Pierre Teilhard de Chardin Wegbereiter des New Age\?
-> wird gefunden

3) Pierre Teilhard de Chardin Wegbe?eiter des New Age
-> wird gefunden

4)hell?
-> scheint für mich korrekte Ergebnisse zu liefern (zum Beispiel helle)

Fragen / Aufgaben
- konsistente Behandlung von ? als Metacharacter

@oschihin: kommt Dir etwas in den Sinn?

**Comment by guenterh** [comment]
weiteres Beipiel:
s. ticket 293

Wenn ich den Titel "Welches Geschlecht hat die Liebe?" eintippe, bekomme ich zwei Treffer für ein Buch Think Limbic, das rein nichts mit dem Gesuchten zu tun hat. Die Broschüre mit diesem Titel (1999), die tatsächlich existiert, kommt jedoch nicht als Treffer. Da muss ein falscher Link gelegt worden sein.
Freundliche Grüsse
xxx

**Comment by witzigs** [comment]
siehe auch swissbib/vufind#380

**Comment by liowalter** [comment]
doesn't show up any more
