### ISSUE TITLE
Verbesserung der Phrasensuche

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#22]
Aus einen user feedback

Guten Morgen Herr xxxx
vielen Dank für Ihr feedback und merci, dass Sie, trotz der zwischendurch auftretenen Unschönheiten in der Suche, immer noch gerne den swissbib service benutzen, obwohl ich Ihnen zwischendurch immer wieder antworten musste, warum die Suche in speziellen Fällen nicht so gut funktioniert. Aus meiner Sicht das positive an den Erklärungen: In der Regel wissen wir, warum etwas nicht so gute Ergebnisse liefert und wir, vor allem weil wir durch den Einsatz von Open Source Technologien hohe Gestaltungsmöglichkeiten, _grundsätzlich_ Verbeserungsmöglichkeiten haben. Zur Zeit haben wir einfach zu wenig Hände, weswegen wir uns manchmal mit nur durchschnittlichen Ergebnissen zufrieden geben. Aber ich will nicht jammern und Ihnen ein paar Hinweise zu geschilderten Suche geben:

Das speziell von Ihnen gesuchte Dokument wurde nicht gefunden, weil Sie nach dem Autor mit einer Phrase gesucht haben.
"Kuno Fiedler". Eine Suche nach den Termen Kuno Fiedler wäre erfolgreich gewesen, allerdings ist die Treffermenge dann grösser.

Was in Ihrem Fall auch funktionieren würde, wäre die Angabe einer sog. adjacency (Abstandsgrösse) der Terme innerhalb der Phrase.
"Kuno Fiedler"~100
Das heisst: die Suchmaschine vertauscht insgesamt hundertmal die Positionen der Terme im Dokument und versucht dadurch ein Ergebnis für die Phrase zu finden
Eine Suche
"Inflation der Menschheit" "Kuno Fiedler"~100
liefert exakt das Dokument

Verkleinert man die Angabe der Abstandsgrösse (Anzahl der Vertauschungen), erhalte ich präzisere Ergebnisse
"Inflation der Menschheit" "kuno fiedler" => 0 Treffer
"Inflation der Menschheit" "Fiedler Kuno" => exakter Treffer (da die Terme in dieser Reihenfolge indexiert wurden)
"Inflation der Menschheit" "Kuno Fiedler"~2 => exakter Treffer (die Maschine hat zweimal versucht, die Positionen zu vertauschen und ist fündig geworden.

Diese Adjanceny Suche ist schlecht dokumentiert. Sie ist für mich auch nur _eine_ Möglichkeit. Es gibt noch eine Reihe weiterer, deren Potential wir noch nicht ausgenutzt haben. Vor allem, ohne dass BenutzerInnen ein Spezialwissen über Suchstrategien haben muss. In diesem Feld ist Google mein (technisches) Vorbild. Wenn wir uns dem annähern können und gleichzeitig, anders als Google, unsere Suchstrategien offenlegen, sind wir nach meiner Ansicht auf dem richtigen Weg.

Ich bin guter Hoffnung, dass wir hier noch einiges liefern können.

Einen guten Tag!

Günter Hipler

Sehr geehrte Damen und Herren
Vorhin habe ich das Buch "Inflation der Menschheit" von Kuno Fiedler gesucht und, da ich den Titel nicht im Kopf hatte, einfach nach "Kuno Fiedler" gesucht. Erstaunlicherweise habe ich das Buch nicht gefunden, obwohl ich es vor einiger Zeit in einer Bibliothek ausgeliehen hatte.
Bei genauerer Prüfung stellte ich fest, dass der Autor im betreffenden Katalogisat als "Fiedler, Kuno" aufgeführt ist und dass die interne Suchmaschine von Swissbib den Titel deswegen nicht gefunden hat.
Vielleicht lässt sie sich so umbauen, dass sie auch in solchen Fällen die Bücher findet?
Freundliche Grüsse
xxxxxx, Basel (ein an sich über swissbib s e h r glücklicher Benutzer)

**Comment by mschwendener** [comment]
> ... wurde nicht gefunden, weil Sie nach dem Autor mit einer Phrase gesucht haben.

Nein: das funktioniert normalerweise prima - wenn der Name denn in der Titelaufnahme so vorkommt. 
Autorenangabe $$c im Feld 245 fehlt. https://www.swissbib.ch/Record/260175773

**Comment by guenterh** [comment]
@mschwendener 
Hallo Manu,
dessen war ich mir bewusst und gleichzeitig ist es der Kern meiner Aussage.
 Mir ist es ziemlich egal, was und wie die Katalogisierung gemacht wird. Mein Anspruch: Die Suchmaschine hat etwas zu finden, auch wenn, wie in diesem Fall halt kein Eintrag in 245c gemacht wurde. 
Da ist Google um Meilen besser - die interessiert so etwas nicht. Die finden einfach...

Günter

**Comment by mschwendener** [comment]
ok :-)

**Comment by liowalter** [comment]
I don't think it is necessary to solve this
Kuno Fiedler
Fiedler Kuno

-> this is fine

"Kuno Fiedler"
"Fiedler Kuno"

don't deliver the same results. Which is intended with the ". Google also delivers different results for such cases.
