### ISSUE TITLE
Behandlung Ampersand in Alle Felder

### ISSUE THREAD

**Issue by witzigs** [swissbib/searchconf#25]
Suche nach Titeln mit Ampersand funktioniert korrekt bei Sucher über Titel, nicht aber bei Suche über Alle Felder

Beispiele:
Society & natural resources
-> in Alle Felder: keine Treffer
-> in Titel: korrekte Treffer

Library & information science abstracts 
-> in Alle Felder: keine Treffer
-> in Titel: korrekte Treffer

**Comment by liowalter** [comment]
will be solved with https://github.com/swissbib/vufind/issues/677
