### ISSUE TITLE
Solr version 6.6 no docValues (30 million documents) local Laptop SSD

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#27]
look at 
https://gist.github.com/guenterh/faa4a52111492b366e216949b31a22ce

- query and response
- solrconfig
- schema
- start script

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [27](https://trello.com/c/pR6EPVip/54-27)

**Comment by guenterh** [comment]
closed for the time being
