### ISSUE TITLE
solr version 4.10 (local laptop) SSD - current production

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#28]
https://gist.github.com/guenterh/8cc0ff6486b7a1ef63abb4d3cd40d097

- first query not cached (response time nearly the same as 6.6 no docvalues)
- second query (fast as expected)
- used schema
- used solrconfig
- used start script

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [28](https://trello.com/c/gKYUbaQ0/55-28)

**Comment by guenterh** [comment]
closed until new experiences

**Comment by guenterh** [comment]
closed for the time being
