### ISSUE TITLE
solr version 6.6 with docvalues and 8 million docs (using facet.threads=4 on multicore machine)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#29]
After getting the hint from BSZ to use facet.threading=4 I made very first test on my multicore laptop
with SSD device (24 G RAM)

swissbib@ub-sbhp02:/usr/local/swissbib/solr/bin$ cat /proc/cpuinfo | grep processor | wc -l
8

swissbib@ub-sbhp02:/usr/local/swissbib/solr/bin$ cat /proc/cpuinfo | grep 'core id' 
core id		: 0
core id		: 0
core id		: 1
core id		: 1
core id		: 2
core id		: 2
core id		: 3
core id		: 3
swissbib@ub-sbhp02:/usr/local/swissbib/solr/bin$ cat /proc/cpuinfo | grep processor
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
processor	: 6
processor	: 7

I tested the facet processing behavior using an index with 8 million docs and docvalues=true
facet.threads=4
The processing time is half the time compared to the request without facet.threading

http://localhost:8080/solr/sb-biblio/select?facet.threads=4&debugQuery=true&q=*:*&indent=on&q.alt=*:*&ps=2&hl=true&bf=recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)&fl=*,score&hl.fragsize=250&q.op=AND&hl.simple.pre={{{{START_HILITE}}}}&qf=title_short^1000+title_alt^200+title^200+title_sub^200+title_old^200+title_new^200+author^750+author_additional^100+author_additional_dsv11_txt_mv^100+title_additional_dsv11_txt_mv^100+author_additional_gnd_txt_mv^100+title_additional_gnd_txt_mv^100+publplace_additional_gnd_txt_mv^100+series^200+topic^500+addfields_txt_mv^50+publplace_txt_mv^25+publplace_dsv11_txt_mv^25+fulltext+callnumber^1000+ctrlnum^1000+publishDate+isbn+cancisbn_isn_mv+variant_isbn_isn_mv+issn+incoissn_isn_mv+localcode+id&hl.fl=fulltext&wt=xml&mm=100%25&facet.field={!ex%3Dunion_filter}union&facet.field={!ex%3DnavAuthor_full_filter}navAuthor_full&facet.field={!ex%3Dformat_hierarchy_str_mv_filter}format_hierarchy_str_mv&facet.field={!ex%3Dlanguage_filter}language&facet.field=navSub_green&facet.field={!ex%3DnavSubform_filter}navSubform&facet.field=publishDate&qt=edismax&json.nl=arrarr&start=0&sort=score+desc&rows=0&facet.limit=50&hl.simple.post={{{{END_HILITE}}}}&spellcheck=false&pf=title_short^1000&facet.mincount=1&facet=true&facet.sort=count

~600 ms

without facet.threads
http://localhost:8080/solr/sb-biblio/select?debugQuery=true&q=*:*&indent=on&q.alt=*:*&ps=2&hl=true&bf=recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)&fl=*,score&hl.fragsize=250&q.op=AND&hl.simple.pre={{{{START_HILITE}}}}&qf=title_short^1000+title_alt^200+title^200+title_sub^200+title_old^200+title_new^200+author^750+author_additional^100+author_additional_dsv11_txt_mv^100+title_additional_dsv11_txt_mv^100+author_additional_gnd_txt_mv^100+title_additional_gnd_txt_mv^100+publplace_additional_gnd_txt_mv^100+series^200+topic^500+addfields_txt_mv^50+publplace_txt_mv^25+publplace_dsv11_txt_mv^25+fulltext+callnumber^1000+ctrlnum^1000+publishDate+isbn+cancisbn_isn_mv+variant_isbn_isn_mv+issn+incoissn_isn_mv+localcode+id&hl.fl=fulltext&wt=xml&mm=100%25&facet.field={!ex%3Dunion_filter}union&facet.field={!ex%3DnavAuthor_full_filter}navAuthor_full&facet.field={!ex%3Dformat_hierarchy_str_mv_filter}format_hierarchy_str_mv&facet.field={!ex%3Dlanguage_filter}language&facet.field=navSub_green&facet.field={!ex%3DnavSubform_filter}navSubform&facet.field=publishDate&qt=edismax&json.nl=arrarr&start=0&sort=score+desc&rows=0&facet.limit=100&hl.simple.post={{{{END_HILITE}}}}&spellcheck=false&pf=title_short^1000&facet.mincount=1&facet=true&facet.sort=count

~ 1.5 sec 

Questions
- what's the recommended server spec to use facet.threads?
- what's the recommended way to define docValues for facets and for sorts. In the reference guide I 
have seen configurations with docValues=true and indexed=false
Why indexed=false?
What's with the stored attribute true or false
- from my point of view I have the impression that solr version 4 makes some caching for facets (second request is really faster than the first one) which doesn't take place with version 6
Is this observation correct? If yes is there something else we can use with version 6

Once we agree on a best approach for our environment we should implement such a definition and use it for a complete reindexing with 30 million docs

**Comment by guenterh** [comment]
response using facet.threads=4


<?xml version="1.0" encoding="UTF-8"?>
<response>

<lst name="responseHeader">
  <int name="status">0</int>
  <int name="QTime">673</int>
  <lst name="params">
    <str name="ps">2</str>
    <str name="hl">true</str>
    <str name="bf">recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)</str>
    <str name="indent">on</str>
    <str name="fl">*,score</str>
    <str name="hl.fragsize">250</str>
    <str name="q.op">AND</str>
    <str name="hl.simple.pre">{{{{START_HILITE}}}}</str>
    <str name="qf">title_short^1000 title_alt^200 title^200 title_sub^200 title_old^200 title_new^200 author^750 author_additional^100 author_additional_dsv11_txt_mv^100 title_additional_dsv11_txt_mv^100 author_additional_gnd_txt_mv^100 title_additional_gnd_txt_mv^100 publplace_additional_gnd_txt_mv^100 series^200 topic^500 addfields_txt_mv^50 publplace_txt_mv^25 publplace_dsv11_txt_mv^25 fulltext callnumber^1000 ctrlnum^1000 publishDate isbn cancisbn_isn_mv variant_isbn_isn_mv issn incoissn_isn_mv localcode id</str>
    <str name="facet.threads">4</str>
    <str name="hl.fl">fulltext</str>
    <str name="wt">xml</str>
    <str name="mm">100%</str>
    <str name="q.alt">*:*</str>
    <arr name="facet.field">
      <str>{!ex=union_filter}union</str>
      <str>{!ex=navAuthor_full_filter}navAuthor_full</str>
      <str>{!ex=format_hierarchy_str_mv_filter}format_hierarchy_str_mv</str>
      <str>{!ex=language_filter}language</str>
      <str>navSub_green</str>
      <str>{!ex=navSubform_filter}navSubform</str>
      <str>publishDate</str>
    </arr>
    <str name="qt">edismax</str>
    <str name="json.nl">arrarr</str>
    <str name="start">0</str>
    <str name="sort">score desc</str>
    <str name="rows">0</str>
    <str name="q">*:*</str>
    <str name="facet.limit">50</str>
    <str name="hl.simple.post">{{{{END_HILITE}}}}</str>
    <str name="spellcheck">false</str>
    <str name="pf">title_short^1000</str>
    <str name="facet.mincount">1</str>
    <str name="facet">true</str>
    <str name="debugQuery">true</str>
    <str name="facet.sort">count</str>
  </lst>
</lst>
<result name="response" numFound="8380237" start="0" maxScore="1.3906972">
</result>
<lst name="facet_counts">
  <lst name="facet_queries"/>
  <lst name="facet_fields">
    <lst name="union">
      <int name="IDS">6671546</int>
      <int name="IDSBB">6262954</int>
      <int name="NEBIS">2174174</int>
      <int name="SNL">1689925</int>
      <int name="RERO">1134914</int>
      <int name="RE61">708036</int>
      <int name="RETROS">638089</int>
      <int name="RE01">597782</int>
      <int name="VAUD">586527</int>
      <int name="IDSLU">530801</int>
      <int name="RE31">339178</int>
      <int name="SGBN">309809</int>
      <int name="IDSSG">277148</int>
      <int name="ABN">266660</int>
      <int name="BGR">163786</int>
      <int name="RE11">160680</int>
      <int name="SBT">138549</int>
      <int name="ALEX">138317</int>
      <int name="LIBIB">94193</int>
      <int name="RE71">69580</int>
      <int name="BORIS">9931</int>
      <int name="SERVAL">3705</int>
      <int name="HEMU">3150</int>
      <int name="ZORA">629</int>
      <int name="RE81">295</int>
      <int name="R001">90</int>
      <int name="NATIONALLICENCE">13</int>
    </lst>
    <lst name="navAuthor_full">
      <int name="SpringerLink (Online service)">28534</int>
      <int name="Schweizerische Normen-Vereinigung">21957</int>
      <int name="ebrary, Inc.">15129</int>
      <int name="Steiner, Rudolf">9795</int>
      <int name="International Monetary Fund">8807</int>
      <int name="IEEE Staff">8725</int>
      <int name="Bach, Johann Sebastian">8116</int>
      <int name="OECD">7470</int>
      <int name="Centre Traditio Litterarum Occidentalium">7343</int>
      <int name="Bongars, Jacques">6934</int>
      <int name="Organisation for Economic Co-operation and Development">6925</int>
      <int name="Mozart, Wolfgang Amadeus">6897</int>
      <int name="England and Wales Parliament.">5621</int>
      <int name="Eidgenössische Landestopographie">5544</int>
      <int name="Electrosuisse">5280</int>
      <int name="Kantonsbibliothek">4997</int>
      <int name="Schweiz, Bundesamt für Landestopografie">4768</int>
      <int name="Beethoven, Ludwig van">4519</int>
      <int name="Stadtbibliothek">4418</int>
      <int name="Hesse, Hermann">4161</int>
      <int name="Internationales Arbeitsamt">3877</int>
      <int name="Great Britain Parliament.">3726</int>
      <int name="Schweizerischer Ingenieur- und Architekten-Verein">3698</int>
      <int name="École polytechnique fédérale de Lausanne">3671</int>
      <int name="Weltgesundheitsorganisation">3607</int>
      <int name="Schweiz, Bundesamt für Statistik">3601</int>
      <int name="Shakespeare, William">3567</int>
      <int name="Haydn, Joseph">3522</int>
      <int name="Vereinte Nationen">3387</int>
      <int name="Schweiz">3322</int>
      <int name="Hochobrigkeitliche Buchdruckerey">3138</int>
      <int name="Stravinsky, Igor">3103</int>
      <int name="Schubert, Franz">3081</int>
      <int name="Schweiz, Bundesrat">3060</int>
      <int name="Händel, Georg Friedrich">3033</int>
      <int name="Goethe, Johann Wolfgang von">2941</int>
      <int name="Cicero, Marcus Tullius">2933</int>
      <int name="Swissmem">2742</int>
      <int name="UNESCO">2724</int>
      <int name="Bern">2687</int>
      <int name="Rilke, Rainer Maria">2644</int>
      <int name="Erasmus, Desiderius">2610</int>
      <int name="Schweiz, Bundesamt für Umwelt, Wald und Landschaft">2589</int>
      <int name="Luther, Martin">2581</int>
      <int name="Rousseau, Jean-Jacques">2579</int>
      <int name="Brahms, Johannes">2547</int>
      <int name="Deutschland">2466</int>
      <int name="Naulais, Jérôme">2370</int>
      <int name="Schumann, Robert">2331</int>
      <int name="Vivaldi, Antonio">2331</int>
    </lst>
    <lst name="format_hierarchy_str_mv">
      <int name="0/XK02/">6339830</int>
      <int name="1/XK02/0000/">6312775</int>
      <int name="0/XK01/">1180360</int>
      <int name="0/XR03/">334110</int>
      <int name="1/XR03/0000/">331263</int>
      <int name="0/XU01/">236908</int>
      <int name="1/XU01/0100/">156445</int>
      <int name="0/XP01/">82260</int>
      <int name="1/XP01/0000/">80428</int>
      <int name="1/XU01/0000/">73566</int>
      <int name="0/XU04/">61091</int>
      <int name="0/XL01/">53523</int>
      <int name="1/XU04/0100/">53074</int>
      <int name="0/XM01/">37410</int>
      <int name="1/XM01/0100/">30495</int>
      <int name="1/XU01/0200/">17294</int>
      <int name="1/XK02/0100/">16125</int>
      <int name="0/XH00/">15670</int>
      <int name="0/XM02/">15010</int>
      <int name="1/XK02/0700/">14423</int>
      <int name="1/XK02/0500/">13026</int>
      <int name="1/XH00/0200/">12531</int>
      <int name="0/XC00/">11864</int>
      <int name="1/XM01/0000/">9022</int>
      <int name="0/XM03/">8224</int>
      <int name="1/XC00/0453/">7902</int>
      <int name="1/XM02/0400/">7500</int>
      <int name="1/XU04/0500/">7028</int>
      <int name="1/XM02/0000/">6937</int>
      <int name="1/XU04/0000/">5213</int>
      <int name="0/XU03/">4648</int>
      <int name="1/XM03/0100/">4370</int>
      <int name="1/XR03/0500/">3705</int>
      <int name="1/XU03/0100/">3158</int>
      <int name="1/XC00/0000/">3048</int>
      <int name="1/XK02/0200/">3032</int>
      <int name="1/XM03/0000/">3011</int>
      <int name="1/XH00/0000/">2858</int>
      <int name="1/XP01/0100/">2030</int>
      <int name="1/XM03/0400/">975</int>
      <int name="1/XU03/0000/">892</int>
      <int name="1/XC00/0100/">809</int>
      <int name="1/XU03/0600/">607</int>
      <int name="1/XM02/0600/">546</int>
      <int name="1/XU04/0600/">383</int>
      <int name="1/XH00/0300/">276</int>
      <int name="1/XU03/0500/">128</int>
      <int name="1/XC00/0500/">121</int>
      <int name="1/XM01/0400/">56</int>
      <int name="1/XM02/0500/">28</int>
    </lst>
    <lst name="language">
      <int name="ger">3493768</int>
      <int name="eng">2144970</int>
      <int name="fre">1121879</int>
      <int name="ita">297488</int>
      <int name="lat">182615</int>
      <int name="zxx">108008</int>
      <int name="spa">102568</int>
      <int name="rus">85170</int>
      <int name="mul">65800</int>
      <int name="dut">35717</int>
      <int name="pol">23736</int>
      <int name="swe">23627</int>
      <int name="grc">20537</int>
      <int name="cze">17805</int>
      <int name="ara">15560</int>
      <int name="gsw">15471</int>
      <int name="hun">15046</int>
      <int name="por">14197</int>
      <int name="dan">11400</int>
      <int name="heb">9991</int>
      <int name="hrv">9500</int>
      <int name="roh">8858</int>
      <int name="nor">7982</int>
      <int name="rum">7203</int>
      <int name="tur">6105</int>
      <int name="cat">5768</int>
      <int name="per">5740</int>
      <int name="gre">5660</int>
      <int name="jpn">5061</int>
      <int name="chi">4386</int>
      <int name="bul">4239</int>
      <int name="fin">4229</int>
      <int name="srp">4096</int>
      <int name="slv">3807</int>
      <int name="ukr">3614</int>
      <int name="slo">3159</int>
      <int name="san">2188</int>
      <int name="lit">1718</int>
      <int name="ind">1441</int>
      <int name="bel">1230</int>
      <int name="ice">1212</int>
      <int name="epo">1091</int>
      <int name="afr">934</int>
      <int name="tib">933</int>
      <int name="ota">918</int>
      <int name="geo">898</int>
      <int name="wel">836</int>
      <int name="est">827</int>
      <int name="lav">817</int>
      <int name="roa">816</int>
    </lst>
    <lst name="navSub_green"/>
    <lst name="navSubform"/>
    <lst name="publishDate">
      <int name="2015">383452</int>
      <int name="2010">288559</int>
      <int name="2011">286045</int>
      <int name="2013">284575</int>
      <int name="2012">283053</int>
      <int name="2014">275665</int>
      <int name="2009">274580</int>
      <int name="2008">273254</int>
      <int name="2007">267913</int>
      <int name="2006">261370</int>
      <int name="2005">257569</int>
      <int name="2004">253176</int>
      <int name="2003">245634</int>
      <int name="1999">244625</int>
      <int name="2002">243708</int>
      <int name="1998">241737</int>
      <int name="2000">241613</int>
      <int name="1997">240965</int>
      <int name="1996">240644</int>
      <int name="1995">240534</int>
      <int name="2001">239486</int>
      <int name="1994">235919</int>
      <int name="1993">228512</int>
      <int name="1992">222335</int>
      <int name="1991">219098</int>
      <int name="1990">217417</int>
      <int name="1989">211246</int>
      <int name="1988">206107</int>
      <int name="1987">201104</int>
      <int name="1986">194490</int>
      <int name="1985">189088</int>
      <int name="1984">184886</int>
      <int name="1983">179941</int>
      <int name="1980">177415</int>
      <int name="1982">177343</int>
      <int name="1981">175238</int>
      <int name="1979">172548</int>
      <int name="1978">168999</int>
      <int name="1977">164888</int>
      <int name="1976">161151</int>
      <int name="1975">157531</int>
      <int name="1974">154667</int>
      <int name="1973">151525</int>
      <int name="1972">147815</int>
      <int name="1970">143427</int>
      <int name="1971">142656</int>
      <int name="1969">137923</int>
      <int name="1968">136223</int>
      <int name="1967">130757</int>
      <int name="1966">125136</int>
    </lst>
  </lst>
  <lst name="facet_ranges"/>
  <lst name="facet_intervals"/>
  <lst name="facet_heatmaps"/>
</lst>
<lst name="highlighting"/>
<lst name="debug">
  <str name="rawquerystring">*:*</str>
  <str name="querystring">*:*</str>
  <str name="parsedquery">(+(+MatchAllDocsQuery(*:*)) () FunctionQuery(100.0/(3.16E-10*float(abs(ms(const(1503878400000),date(freshness))))+100.0)))/no_coord</str>
  <str name="parsedquery_toString">+(+*:*) () 100.0/(3.16E-10*float(abs(ms(const(1503878400000),date(freshness))))+100.0)</str>
  <lst name="explain"/>
  <lst name="facet-debug">
    <long name="elapse">672</long>
    <arr name="sub-facet">
      <lst>
        <str name="processor">SimpleFacets</str>
        <long name="elapse">672</long>
        <str name="action">field facet</str>
        <int name="maxThreads">4</int>
        <arr name="sub-facet">
          <lst/>
          <lst/>
          <lst/>
          <lst>
            <str name="requestedMethod">not specified</str>
            <str name="appliedMethod">FC</str>
            <int name="inputDocSetSize">8380237</int>
            <str name="field">navAuthor_full</str>
            <int name="numBuckets">2836189</int>
          </lst>
          <lst>
            <long name="elapse">209</long>
            <str name="requestedMethod">not specified</str>
            <str name="appliedMethod">FC</str>
            <int name="inputDocSetSize">8380237</int>
            <str name="field">language</str>
            <int name="numBuckets">401</int>
          </lst>
          <lst>
            <long name="elapse">0</long>
            <str name="requestedMethod">not specified</str>
            <str name="appliedMethod">FC</str>
            <int name="inputDocSetSize">8380237</int>
            <str name="field">navSub_green</str>
          </lst>
          <lst>
            <long name="elapse">462</long>
            <str name="requestedMethod">not specified</str>
            <str name="appliedMethod">FC</str>
            <int name="inputDocSetSize">8380237</int>
            <str name="field">publishDate</str>
            <int name="numBuckets">1023</int>
          </lst>
        </arr>
      </lst>
    </arr>
  </lst>
  <str name="QParser">ExtendedDismaxQParser</str>
  <null name="altquerystring"/>
  <null name="boost_queries"/>
  <arr name="parsed_boost_queries"/>
  <arr name="boostfuncs">
    <str>recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)</str>
  </arr>
  <lst name="timing">
    <double name="time">673.0</double>
    <lst name="prepare">
      <double name="time">0.0</double>
      <lst name="query">
        <double name="time">0.0</double>
      </lst>
      <lst name="facet">
        <double name="time">0.0</double>
      </lst>
      <lst name="facet_module">
        <double name="time">0.0</double>
      </lst>
      <lst name="mlt">
        <double name="time">0.0</double>
      </lst>
      <lst name="highlight">
        <double name="time">0.0</double>
      </lst>
      <lst name="stats">
        <double name="time">0.0</double>
      </lst>
      <lst name="expand">
        <double name="time">0.0</double>
      </lst>
      <lst name="terms">
        <double name="time">0.0</double>
      </lst>
      <lst name="spellcheck">
        <double name="time">0.0</double>
      </lst>
      <lst name="debug">
        <double name="time">0.0</double>
      </lst>
    </lst>
    <lst name="process">
      <double name="time">672.0</double>
      <lst name="query">
        <double name="time">0.0</double>
      </lst>
      <lst name="facet">
        <double name="time">672.0</double>
      </lst>
      <lst name="facet_module">
        <double name="time">0.0</double>
      </lst>
      <lst name="mlt">
        <double name="time">0.0</double>
      </lst>
      <lst name="highlight">
        <double name="time">0.0</double>
      </lst>
      <lst name="stats">
        <double name="time">0.0</double>
      </lst>
      <lst name="expand">
        <double name="time">0.0</double>
      </lst>
      <lst name="terms">
        <double name="time">0.0</double>
      </lst>
      <lst name="spellcheck">
        <double name="time">0.0</double>
      </lst>
      <lst name="debug">
        <double name="time">0.0</double>
      </lst>
    </lst>
  </lst>
</lst>
</response>

**Comment by guenterh** [comment]
[facet.threads.4.txt](https://github.com/swissbib/searchconf/files/1257491/facet.threads.4.txt)

**Comment by guenterh** [comment]
[no.facet.threads.txt](https://github.com/swissbib/searchconf/files/1257496/no.facet.threads.txt)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [29](https://trello.com/c/vjrYQgfq/56-29)

**Comment by guenterh** [comment]
closed until we get new experiences
