### ISSUE TITLE
findings from various sources

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#30]
Hi Günter,

I've tried facet.threads with different facet methods, but can't see a difference. However this index has docValues, so that may be the factor.

I also resurrected Solr 4.10 and I'm now building a couple of test indexes with and without docValues. As far as I remember, there's a bug in several Solr versions where facet.method is not honored which makes it impossible to bypass docValues when they're available. I can't check exactly as Apache's JIRA seems to be unavailable at the moment.

Anyway, my test is already showing a radically different result for the index versions though the index without docValues isn't complete yet: with docValues the faceting time is always proportional to the index size, while without docValues it's still blazing fast (24ms) with 11 million records. Looking at the cache stats shows that without docValues the fieldValueCache is being used, but with docValues it stays empty and has no lookups.

I already tried an index without docValues with Solr 6.6.0, and it didn't show the above difference. I'll do another round of testing to make sure and will also take a look at fieldValueCache behavior. I'll make sure to re-test facet.threads too.

--Ere

Günter Hipler kirjoitti 28.8.2017 klo 18.48:
> Hi Ere,
>
> first finding:
>
> I got the hint from Stefan Winkler (BSZ) to add facet.threads=4 (4 as example)
>
> My quick experience: It boosts the facet processing but only with docValues=false. Actually with docValues=true I don't have an improvement (very first test)
>
> Without docvalues It's still slower compared to version 4 but makes it better roughly from 4.5 to 3 sec (30 million docs)
>
> Could you give it a try in your environment?
>
> Thanks and best wishes
>
> Günter

**Comment by guenterh** [comment]
yesterday evening I started the re-build of the index on sb-us15 with now 8 million docs and docValues but indexed=false
With facet.threads=4 I got an improvement but this was less compared to my local laptop with 4 cores (sb-us15 had 2 cores)
Then I increased the number of cores to 3 on sb-us15 now I get results with around 700 ms

for the query
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet.threads=4&q=*:*&facet.field=union&facet.field=navAuthor_full&facet.field=format&facet.field=language&facet.field=navSub_green&facet.field=navSubform&facet.field=publishDate&qt=edismax&ps=2&hl=true&json.nl=arrarr&bf=recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)&fl=*,score&hl.fragsize=250&start=0&q.op=AND&sort=score+desc&rows=20&hl.simple.pre={{{{START_HILITE}}}}&facet.limit=100&hl.simple.post={{{{END_HILITE}}}}&spellcheck=false&qf=title_short^1000+title_alt^200+title_sub^200+title_old^200+title_new^200+author^750+author_additional^100+author_additional_dsv11_txt_mv^100+title_additional_dsv11_txt_mv^100+series^200+topic^500+addfields_txt_mv^50+publplace_txt_mv^25+publplace_dsv11_txt_mv^25+fulltext+callnumber^1000+ctrlnum^1000+publishDate+isbn+variant_isbn_isn_mv+issn+localcode+id&pf=title_short^1000&facet.mincount=1&hl.fl=fulltext&facet=true&wt=xml&facet.sort=count

which is only slightly worse compared to my local machine (between 600 and 700 ms)

**Comment by guenterh** [comment]
Info from Ere (29.8.2017)
A quick follow-up:

With Solr 6.6.0 an index with docValues="false" and 2.5 million records is already a few times slower than the 4.1 index (docValues="false") that now contains 17.5 million records. I was able to make the 6.6.0 index access the fieldValueCache by specifying facet.method=uif (this seems to be undocumented but is mentioned in Solr's CHANGES.txt), but it's even slower than the default method FC. Increasing facet.threads with or without facet.method=enum only increases the faceting time.

--Ere 

my comment:
I used facet.method=uif on sb-us15 (docvalues=true ( indexed=false) 8 millions
--> and had no effect (nearly the same as facet.method=fc)

**Comment by guenterh** [comment]
Hallo Herr Hipler,


ich habe nun doch ein paar Minuten Zeit gehabt mir Ihr Problem anzusehen.

Das war zwar noch keine vollständige Analyse, jedoch ist mir ein "QuickWin" für Sie aufgefallen.


Einige Felder, wie beispielsweise "publishDate" oder "language" eignen sich dafür die "facet.method" zu ändern.
Aktuell wird für jede Facette ein Eintrag im FieldCache (facet.method=fc) erzeugt. Bei Feldern mit "wenigen" unterschiedlichen Werten kann es performanter sein, auf "facet.method=enum" zu wechseln.
Bei dieser Variante wird für jeden Wert im Feld ein separater Eintrag im FilterCache generiert.

Nachfolgend ein paar Beispiel-Requests, die ich gemacht hab:

Feld "language"
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=language&debugQuery=true&q=*:*&rows=0&facet.method=fc [^] -> ca 180 ms (bei Wiederholung des Request: ca 180 ms)
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=language&debugQuery=true&q=*:*&rows=0&facet.method=enum [^] -> ca 80 ms (bei Wiederholung des Request: ca 3 ms)

Feld "publishDate"
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=publishDate&debugQuery=true&q=*:*&rows=0&facet.method=fc [^] -> ca 535 ms (bei Wiederholung des Request: ca 535 ms)
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=publishDate&debugQuery=true&q=*:*&rows=0&facet.method=enum [^] -> ca 225 ms (bei Wiederholung des Request: ca 25 ms)


In dieser Variante profitieren Sie vor allem von den Einträgen im FilterCache, da es hier nochmals (bei der Wiederholung des Request) eine deutliche Verbesserung gibt.


Feld "publishDate" & "language"
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=language&facet.field=publishDate&debugQuery=true&q=*:*&rows=0&facet.method=fc [^] -> ca 725 ms (bei Wiederholung des Request: ca 725 ms)
http://sb-us15.swissbib.unibas.ch:8080/solr/sb-biblio/select?facet=true&facet.field=language&facet.field=publishDate&debugQuery=true&q=*:*&rows=0&facet.method=enum [^] ca 350 ms (bei Wiederholung des Request: ca 350 ms)

Bei beiden Feldern gleichzeitig gibt es auch eine Verbesserung der Antwortzeit, jedoch fällt diese nicht ganz so deutlich aus.
Dies liegt aber daran, dass in diesem Fall der FilterCache zu klein ist um die Einträge für beide Felder zu halten. Somit kommt es während eines Requests zu Inserts und Evictions.
Sollten Sie diesen Ansatz weiter verfolgen sollten Sie die Größe des Caches entsprechend anpassen.


Für Fragen stehe ich Ihnen gerne zur Verfügung.

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [30](https://trello.com/c/tmLNz4Qn/57-30)

**Comment by guenterh** [comment]
closed for the time being
