### ISSUE TITLE
Suche über callnumber: keine Treffer bei BB

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#32]
Bekam heute einen Anruf vom ITS. Jemand (Andreas) sucht nach Literatur (DDC) und fand nichts.
Habe ihn dann auf die erweiterte Suche (callnumber) verwiesen

Mit 025.431 findet man bei green etwas jedoch ncht bei BB - warum? Treffer in green hatten Institutionen von Bern

@witzigs weisst Du warum?

**Comment by guenterh** [comment]
Zusatz: von der Info bekam Andreas die Aussage, dass solche Suchen nicht möglich sind. Sollen / müssen wir daran arbeiten (mehr Info an andere oder Suche verbessern?)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [32](https://trello.com/c/freERwzI/59-32)

**Comment by witzigs** [comment]
@guenterh 
Die Signaturen mit der gesuchten DDC sind im Basel Bern Index nicht vorhanden, da sie nicht aus Basel Bern stammen. Die Basel-Berner-Exemplare haben andere Signaturen.
