### ISSUE TITLE
VF4 -> Solr7 (1)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#34]
Because cloud doesn't work with core (only collections) there seems to be a problem building the SOLR URL
https://github.com/swissbib/vufind/blob/master/module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php#L345

creates

[base]/solr/green//select....

double slash causes an error

Is there a special configuration in VuFind for collections in SOLR

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [34](https://trello.com/c/v6TR1SGf/61-34)

**Comment by guenterh** [comment]
s. https://github.com/swissbib/searchconf/issues/43
