### ISSUE TITLE
VF4 -> SOLR7 (2)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#35]
actually similar items in full view are not shown with SOLR 7

Configuration in SOLR or problem with VF?

**Comment by guenterh** [comment]
seems not to be a problem of SOLR configuration but of the item being searched

https://develop.swissbib.ch/Record/134535383/Similar#tabnav
shows similar items in the tab
while this
https://develop.swissbib.ch/Record/258446668/Similar#tabnav
shows nothing

**Comment by guenterh** [comment]
hmh, worth - sometimes items are shown sometimes not.... (for the same URI)

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [35](https://trello.com/c/KNLIN9Xw/62-35)

**Comment by guenterh** [comment]
s. https://github.com/swissbib/searchconf/issues/43
