### ISSUE TITLE
Boolsche Operatoren mit solr 7

### ISSUE THREAD

**Issue by witzigs** [swissbib/searchconf#36]
###Boolsche Operatoren
brand AND marketing: 4319 (vufind und solr)
+brand +marketing: 4319 (vufind und solr)
brand and marketing: 1866 (vufind), 1849 (solr) 
brand marketing: 3392 (vufind), 3357 (solr) -> http://localhost:8015/solr/green/select?bf=recip(abs(ms(NOW/DAY,freshness)),3.16e-10,100,100)&defType=edismax&mm=100%&pf=title_short^1000&ps=2&q=brand%20marketing&qf=title_short^1000%20title_alt^200%20title_sub^200%20title_old^200%20title_new^200%20author^750%20author_additional^100%20author_additional_dsv11_txt_mv^100%20title_additional_dsv11_txt_mv^100%20author_additional_gnd_txt_mv^100%20title_additional_gnd_txt_mv^100%20publplace_additional_gnd_txt_mv^100%20series^200%20topic^500%20addfields_txt_mv^50%20publplace_txt_mv^25%20publplace_dsv11_txt_mv^25%20fulltext%20callnumber^1000%20ctrlnum^1000%20publishDate%20isbn%20variant_isbn_isn_mv%20issn%20localcode%20id
brand UND marketing: 571 (vufind), 570 (solr)
-> nok: Unterschiedliche Treffermengen vufind/solr

brand OR marketing: 4319 (vufind und solr) -> gleiche Treffer wie bei brand AND marketing
brand or marketing: 788
-> nok: OR-Operator funktioniert nicht

brand NOT marketing: 19868 (vufind und solr) -> die ersten drei Treffer sollten nicht da sein, sonst siehts gut aus -> ist wegen der Signatur "B RAND", diese wird im Ranking gepusht...
brand -marketing: 19868 (vufind und solr)
-> ok

###Erweiterte Suche
einzeln alle ok
1 Gruppe mit OR: ok
1 Gruppe mit AND: ok
1 Gruppe mit NOT: nok, liefert keine Treffer -> funktioniert auf Produktion
2 Gruppen mit AND: ok
2 Gruppen mit OR: ok
2 Gruppen mit NOT: ok

**Comment by swissbib-unibas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [36](https://trello.com/c/xrsu2YbM/63-36)

**Comment by guenterh** [comment]
s. https://github.com/swissbib/searchconf/issues/43

**Comment by witzigs** [comment]
Update 

###Boolsche Operatoren
brand AND marketing: 4388 (vufind und solr)  -> OK
+brand +marketing: 4388 (vufind und solr)  -> OK
brand and marketing: 2961 (vufind und solr) -> OK
brand marketing: 4388 (vufind und solr)  -> OK

brand OR marketing: 4388 (vufind), 104058 (solr ohne mm 100) -> NOK

brand NOT marketing: 22912 (vufind und solr, mit und ohne mm 100) -> OK

**Comment by guenterh** [comment]
sind ok, nachdem wir den mm operator aus der searchspec entfernt haben
