### ISSUE TITLE
Tests mit VuFind 4 gegen SOLR7 (allgemein)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#43]

**Comment by guenterh** [comment]
s. auch
https://github.com/swissbib/searchconf/issues/36
https://github.com/swissbib/searchconf/issues/34
https://github.com/swissbib/searchconf/issues/33

**Comment by guenterh** [comment]
aufgefallene Dinge

* ist der Handler similarItems definiert? Ich bekomme keine Anzeige

**Comment by guenterh** [comment]
s. zu MLT Parser auch https://github.com/swissbib/vufind/issues/625

**Comment by liowalter** [comment]
closed via https://github.com/swissbib/vufind/issues/625
