### ISSUE TITLE
better relevance in solr4 instead of solr7 ?

### ISSUE THREAD

**Issue by liowalter** [swissbib/searchconf#52]
In this case : 

- http://devbabe.swissbib.ch/Search/Results?lookfor=Erich+K%C3%A4stner+Gedichte&type=AllFields&filter%5B%5D=%7Eformat_hierarchy_str_mv%3A%220%2FXK02%2F%22
- https://baselbern.swissbib.ch/Search/Results?lookfor=Erich+K%C3%A4stner+Gedichte&type=AllFields&filter[]=~format_hierarchy_str_mv%3A%220%2FXK02%2F%22

??

**Comment by witzigs** [comment]
@guenterh 
Ist die "alte" Relevanzberechnung aktiv?
Wir hatten das schon ähnlich gesehen, als Sonja auf Solr 6 getestet hat. Und ich meine das hätte sich gebessert als wir statt BM25 wieder die alte Berechnung aktivert haben.

**Comment by guenterh** [comment]
@witzigs 
Ich schaue es mir an (habe es gerade nur kurz getan).
Releavant ist
https://lucene.apache.org/solr/guide/7_4/other-schema-elements.html#similarity
Das entsprechende file auf den servern
https://solrgreendev.swissbib.ch/solr/#/green/files?file=solrconfig.xml
https://solrbbdev.swissbib.ch/solr/#/bb/files?file=solrconfig.xml 

@liowalter 
Perhaps a good use case for you to get more practice in using the API?

**Comment by guenterh** [comment]
@witzigs @liowalter 
Ich habe jetzt mal genauer nachgeschaut - auf SOLR7 ist das klassische similarity Verfahren eingestellt (TF/IDF und nicht BM25)

![classic_similarity](https://user-images.githubusercontent.com/1825990/45948293-b63bcd80-bff7-11e8-998e-0ce6e755a89d.png)

Das Problem scheint mir aber nicht das ranking sondern die deutlich geringere Trefferzahl zu sein. Beim scrollen durch die Liste habe ich die beiden Gedichte Treffer z.B. nicht gefunden. (s. auch die beiden folgenden screenshots) Wir müssen also die Ursache finden, warum soviel weniger Treffer zurückgegeben werden. Ich werde dafür auch die Suchmaschinen mit den Daten des letzten Exports laden.


![bb old ranking](https://user-images.githubusercontent.com/1825990/45948404-21859f80-bff8-11e8-85eb-2110bab38971.png)

![bb new ranking](https://user-images.githubusercontent.com/1825990/45948408-26e2ea00-bff8-11e8-9940-64092334057c.png)

**Comment by guenterh** [comment]
vergleiche 
https://github.com/swissbib/vufind/issues/645#issuecomment-424048818
scheint mir ähnliche Problematik zu sein

**Comment by guenterh** [comment]
@witzigs @liowalter @chantalw zur Info
Zwei Dinge haben das Suchverhalten entscheidend verbessert
- [Anpassungen in solrconfig.xml](https://github.com/swissbib/vufind/issues/645)
- Neuindexierung mit aktuellem Export aus CBS
Die oben angegebenen Abfragen liefern nun die gleiche Treffermenge (94 Dokumente) und das Ranking ist nahezu identisch
