### ISSUE TITLE
Anpassen der Indexerkonfigurationen für zweiten (Fallbackcluster)

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#55]
- nach dem Aufbau des Fallbackclusters für green und bb (mit den Maschinen des alten SOLR4) müssen: 

alle Konfigurationen, die mit der Indexieung gegen die cluster zu tun haben, so angepasst werden, dass beide cluster mit den Dokumenten aktualisiert werden

- sb-us9
-- /swissbib_index/solrDocumentProcessing/MarcToSolr/dist/postclient/app.properties
(zweites Zookeeperensemble)
-- HAN Daten Indexing (nur auf sb-us9) 
/swissbib_index/solrDocumentProcessing/MarcToSolr/dist/processHANDataSearchDocs.py
s. auch https://github.com/swissbib/searchconf/issues/54#issuecomment-424753794

- sb-us10
-- /swissbib_index/solrDocumentProcessing/MarcToSolr/dist/postclient/app.properties
(zweites Zookeeperensemble)

**Comment by liowalter** [comment]
@guenterh : can this be closed ?

**Comment by guenterh** [comment]
done
