### ISSUE TITLE
Anpassen workflow regelmässiger Indexupdate 

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#56]
Für den regelmässigen post der verschiedenen Dokumente nach SOLR
- update
- delete im update Prozess
- sog. "weeded documents" - gilt nur für BB aufgrund der eingeschränkten view auf records, die im CBS Master/Slave Prozess erstell werden
verwenden wir zurzeit zwei Python - scripte, die sich aber in grossen Teilen ähneln.
Kommt hinzu, dass durch die zukünftige ausschliessliche verwendung des neuen auf MF basierenden Indexerclients, sich das Handling der Dokumente bereits vereinfacht (wird noch besser, wenn der workflow komplett auf MF umgestellt sein wird)

* Ich gehe davon aus, dass nach dem Update zu SOLR7 die beiden scripte zuerst gemerged und das verbliebene sehr vereinfacht werden kann.

https://github.com/swissbib/content2SearchDocs/blob/switchMaster2Gradle/shellscripts/post2SolrFrequent.py
https://github.com/swissbib/content2SearchDocs/blob/switchMaster2Gradle/shellscripts/post2SolrWeedings.py

**Comment by liowalter** [comment]
@guenterh : I guess that this can be closed ?

**Comment by guenterh** [comment]
done
