### ISSUE TITLE
Suche mit ? als Teil der Suchterms liefert 0 Treffer

### ISSUE THREAD

**Issue by guenterh** [swissbib/searchconf#57]
Eine Suche nach

Good by shôsetsu, hello again, monogatari ? the validity of restoring contextuality in prose

liefert 0 Treffer (und dauert sehr lange)
aufgrund des Fragezeichens
dies sollte nicht sein

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[searchconf] Suche mit ? als Teil der Suchterms liefert 0 Treffer](https://trello.com/c/LHQ1aWQf/321-searchconf-suche-mit-als-teil-der-suchterms-liefert-0-treffer)

**Comment by liowalter** [comment]
Good by shôsetsu, hello again, monogatari ? the validity of restoring contextuality in prose : no result
Good by shôsetsu, hello again, monogatari the validity of restoring contextuality in prose : one result

I have the feeling that ? is taken as "any word of one letter".

Search ? gives all swissbib
Search " ? " gives only a subset

**Comment by liowalter** [comment]
q sent to solr by vufind : Head first learn to code a brain-friendly guide "/" Eric Freeman

**Comment by liowalter** [comment]
fixed with https://github.com/swissbib/vufind/commit/0647f930bab2ca81489a3e2e8dbc813c5c796f48
