### ISSUE TITLE
requestHandler /terms is doppelt definiert in solrconfig.xml

### ISSUE THREAD

**Issue by zazi** [swissbib/searchconf#59]
siehe [#L218](https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/solrconfig.xml#L218) und [#528](https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/solrconfig.xml#L528) in [dieser solrconfig.xml](https://github.com/swissbib/searchconf/blob/master/solr/bib/solr.home/conf/solrconfig.xml)

die Frage ist, welche Definition davon greift eigentlich bzw. muss die referenzierte searchComponent schon vorher definiert sein (ich glaube fast ja)

**Comment by guenterh** [comment]
@zazi 
Guten Morgen Thomas,
Danke für den Hinweis!
Ein wenig praktische Umsetzung Deines Blogkommentars (https://twitter.com/smiysmiysmiy/status/1049287319658926080). Wollte eigentlich auch noch was dazu aus meiner Sicht geschrieben haben, komm irgendwie zu selten zu solchen Dingen. Freut mich auf jeden Fall, wieder etwas von Dir gehört zu haben. Bist Du an der swib?
Wir wollen bis Ende des Monats auf SOLR7 wechseln. Endlich ist dieser alte Sch.... dann weg
@liowalter z.I.
@edelm: ich verteile die neue Version gleich noch auf die cluster green und bb. Kannst Du Dich um https://github.com/swissbib/vufind/issues/657 kümmern?

**Comment by guenterh** [comment]
@liowalter @witzigs @edelm 
ich beschreibe in dem internen repository
git@git.swissbib.ch:~/doku.infrastruktur
die Abläufe von solchen Prozessen mit den neuen SOLR7 clustern.
das Update der Konfigurationen habe ich im Dokument solr7/nutzung.solr.apis.md
unter
"Beispiele für benutzte Befehle" 2) 
festgehalten.
Verständlich?
